// Web SDK/Player Integrations/Video.js/React.js/src/components/Player.jsx
import {useEffect, useRef} from 'react';

import 'video.js/dist/video-js.css';

import {driver} from '@mlytics/p2sp-sdk/driver/peripheral/player/videojs/streaming/hls/bundle';

const Player = (props) => {
    const videoRef = useRef(null);
    const playerRef = useRef(null);
    const {options} = props;

    useEffect(() => {
        const video = videoRef.current;
        if (!playerRef.current) {
            const adapter = driver.extensions.VideojsHlsPlayerPlugin.create(video, options);
            playerRef.current = adapter.player;
        } else {
            const player = playerRef.current;
            player.src(options.sources);
        }
    }, [options, videoRef]);

    useEffect(() => {
        const player = playerRef.current;
        return () => {
            if (player && !player.isDisposed()) {
                player.dispose();
                playerRef.current = null;
            }
        };
    }, [playerRef]);

    return <div data-vjs-player>
        <video ref={videoRef} className="video-js" style={{width: "100%", maxWidth: "800px"}} />
    </div>;
};
export default Player;

// Web SDK/Player Integrations/Video.js/Vue.js/src/components/Player.vue
<template>
    <div>
        <video ref="video" class="video-js" style="width: 100%; maxWidth: 800px"></video>
    </div>
</template>

<script>
/* eslint-disable vue/multi-word-component-names */

import 'video.js/dist/video-js.css';

import {driver} from '@mlytics/p2sp-sdk/driver/peripheral/player/videojs/streaming/hls/bundle';

export default {
    name: 'Player',
    props: {
        options: {
            type: Object
        }
    },
    data() {
        return {
            player: null
        };
    },
    mounted() {
        const adapter = driver.extensions.VideojsHlsPlayerPlugin.create(this.$refs.video, this.options);
        this.player = adapter.player;
    },
    beforeUnmount() {
        if (this.player) {
            this.player.dispose();
        }
    }
};
</script>
