// Web SDK/Player Integrations/DPlayer/React.js/src/components/Player.js
import React, {
    useEffect,
    useRef
} from 'react';

import {
    driver
} from '@mlytics/p2sp-sdk/driver/peripheral/player/dplayer/streaming/hls/bundle';

const Player = (props) => {
    const videoRef = useRef(null);
    const dpRef = useRef(null);
    const {
      options
    } = props

    useEffect(() => {
        const video = videoRef.current;
        if (!dpRef.current) {
          const adapter = driver.extensions.DPlayerHlsPlayerPlugin.create({
            container: video,
            ...options
          });
          dpRef.current = adapter.player;
        }
    }, [videoRef]);

    useEffect(() => {
        const dp = dpRef.current;
        return () => {
          if (dp) {
            dp.destroy();
            dpRef.current = null;
          }
        };
    }, [dpRef]);

  return (
    <div id="video" ref={videoRef} style={{width: "100%", maxWidth: "800px"}} />
  );
};
export default Player;

// DPlayer/vue-sample/src/components/Player.vue
<template>
  <div id="video" ref="videoRef" style="width: 100%; maxWidth: 800px" />
</template>

<script>
import { driver } from '@mlytics/p2sp-sdk/driver/peripheral/player/dplayer/streaming/hls/bundle';

export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Player',
  props: {
    options: {
      type: Object
    }
  },
  data() {
    return {
      dp: null
    };
  },
  async mounted() {
    const video = this.$refs.videoRef;

    const adapter = driver.extensions.DPlayerHlsPlayerPlugin.create({
      container: video,
      ...this.options
    });

    this.dp = adapter.player;
  },
  async beforeUnmount() {
    if (this.dp) this.dp.destroy();
  }
};
</script>
