// Web SDK/Player Integrations/DPlayer/React/npm/src/App.js
import React, {useEffect, useState} from 'react';

import DPlayer from 'dplayer';

import {driver, DPlayerHlsPlugin} from '@mlytics/p2sp-sdk/driver/peripheral/player/dplayer/streaming/hls/bundle';

import './App.css';
import Player from './components/Player';

DPlayerHlsPlugin.register(DPlayer);

const App = () => {
    const [options, setOptions] = useState(null);

    useEffect(() => {
        driver.initialize();
        setOptions({
            autoplay: true,
            video: {
                url: 'https://1001642588942-cloudfront-z6frgspx.d-apm.com/hls/5ec5f77c-ba77-4054-af5a-90431f7e9904.mp4/5ec5f77c-ba77-4054-af5a-90431f7e9904.m3u8'
            },
        });
    }, []);

    return (
        <div className="App">
            <header className="App-header">
                {options ? <Player options={options} /> : null}
            </header>
        </div>
    );
};

export default App;

// Web SDK/Player Integrations/DPlayer/Vue.js/src/App.vue
<template>
  <Player :options="videoOptions" />
</template>

<script>
import DPlayer from 'dplayer'

import { driver, DPlayerHlsPlugin } from '@mlytics/p2sp-sdk/driver/peripheral/player/dplayer/streaming/hls/bundle';

import Player from './components/Player.vue';


DPlayerHlsPlugin.register(DPlayer);

export default {
  name: 'App',
  components: {
    Player
  },
  setup() {
    driver.initialize();
  },
  data() {
    return {
      videoOptions: {
        autoplay: true,
        controls: true,
        video: {
          url: 'https://1001642588942-cloudfront-z6frgspx.d-apm.com/hls/5ec5f77c-ba77-4054-af5a-90431f7e9904.mp4/5ec5f77c-ba77-4054-af5a-90431f7e9904.m3u8',
        }
      }
    };
  }
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
