// Web SDK/Player Integrations/HLS.js/React.js/src/components/Player.js
import {useEffect, useRef} from 'react';
import {driver} from '@mlytics/p2sp-sdk/driver/peripheral/player/hlsjs/streaming/hls/bundle';

const Player = (props) => {
  const videoRef = useRef(null);
  const hlsRef = useRef(null);

  useEffect(() => {
    const {sourceUrl} = props.options;
    const video = videoRef.current;
    if (!hlsRef.current) {
      const adapter = driver.extensions.HlsjsHlsPlayerPlugin.create({
        url: sourceUrl,
        element: video
      });
      hlsRef.current = adapter.protocol;
    }
  }, [videoRef]);

  useEffect(() => {
    const hls = hlsRef.current;
    return () => {
      if (hls) {
        hls.destroy();
        hlsRef.current = null;
      }
    };
  }, [hlsRef]);

  return (
    <video
      controls
      autoPlay
      ref={videoRef}

      width={800}
    />
  );
};
export default Player;

// HLS.js/vue-sample/src/components/Player.vue
<template>
  <video id="video" ref="videoRef" controls autoplay width=800 />
</template>

<script>
import { driver } from '@mlytics/p2sp-sdk/driver/peripheral/player/hlsjs/streaming/hls/bundle';

export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Player',
  props: {
    options: {
      type: Object
    }
  },
  data() {
    return {
      hls: null
    };
  },
  async mounted() {
    const video = this.$refs.videoRef;
    const {sourceUrl} = this.options;
    const adapter = driver.extensions.HlsjsHlsPlayerPlugin.create({
      url: sourceUrl,
      element: video
    });
    this.hls = adapter.protocol;
  },
  async beforeUnmount() {
    if (this.hls) {
      this.hls.destroy();
    }
  }
};
</script>
