// HLS.js/react-sample/src/components/Player.js
import { useEffect, useRef } from 'react';
import { HlsjsHlsPlugin } from '@mlytics/p2sp-sdk/driver/peripheral/player/hlsjs/streaming/hls/bundle';

const Player = (props) => {
  const videoRef = useRef(null);
  const hlsRef = useRef(null);

  useEffect(() => {
    const hls = hlsRef.current;
    return () => {
      if (hls) {
        hls.destroyed();
      }
    }
  }, []);

  useEffect(() => {
    const { sourceUrl } = props.options;
    const video = videoRef.current;
    hlsRef.current = HlsjsHlsPlugin.create({
      sourceUrl: sourceUrl,
      mediaElement: video,
      playerConfig: {}
    });
  }, [videoRef]);

  return (
    <video
      controls
      autoPlay
      ref={videoRef}

      width={800}
    />
  );
}
export default Player;

// HLS.js/vue-sample/src/components/Player.vue
<template>
  <video id="video" ref="videoRef" controls autoplay width=800 />
</template>

<script>
import { HlsjsHlsPlugin } from '@mlytics/p2sp-sdk/driver/peripheral/player/hlsjs/streaming/hls/bundle';

export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Player',
  props: {
    options: {
      type: Object
    }
  },
  data() {
    return {
      hls: null
    };
  },
  async mounted() {
    const video = this.$refs.videoRef;
    const { sourceUrl } = this.options;
    this.hls = HlsjsHlsPlugin.create({
      sourceUrl: sourceUrl,
      mediaElement: video,
      playerConfig: {}
    });
  },
  async beforeUnmount() {
    if (this.hls) {
      this.hls.destroy();
    }
  }
};
</script>
