// Web SDK/Player Integrations/HLS.js/Vue/html/src/App.vue
<template>
    <Player :options="videoOptions" />
</template>

<script>
import Player from './components/Player.vue';

export default {
    name: 'App',
    components: {
        Player
    },
    beforeMount() {
        self.mlysdk.driver.initialize();
    },
    data() {
        return {
            videoOptions: {
                sourceUrl: 'https://1001642588942-cloudfront-z6frgspx.d-apm.com/hls/5ec5f77c-ba77-4054-af5a-90431f7e9904.mp4/5ec5f77c-ba77-4054-af5a-90431f7e9904.m3u8'
            }
        };
    }
};
</script>

<style>
#app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
}
</style>

// Web SDK/Player Integrations/DPlayer/React/html/src/App.js
import React, {useEffect, useState} from 'react';

import './App.css';
import Player from './components/Player';

const App = () => {
    const [options, setOptions] = useState(null);
    useEffect(() => {
        self.mlysdk.driver.initialize();
        setOptions({
            autoplay: true,
            video: {
                url: 'https://1001642588942-cloudfront-z6frgspx.d-apm.com/hls/5ec5f77c-ba77-4054-af5a-90431f7e9904.mp4/5ec5f77c-ba77-4054-af5a-90431f7e9904.m3u8'
            },
        });
    }, []);

    return (
        <div className="App">
            <header className="App-header">
                {options ? <Player options={options} /> : null}
            </header>
        </div>
    );
};

export default App;
