// Web SDK/Player Integrations/DPlayer/Vue/html/src/components/Player.vue
<template>
    <div id="video" ref="videoRef" style="width: 100%; maxWidth: 800px" />
</template>

<script>
/* eslint-disable vue/multi-word-component-names */

export default {
    name: 'Player',
    props: {
        options: {
            type: Object
        }
    },
    data() {
        return {
            dp: null
        };
    },
    async mounted() {
        const video = this.$refs.videoRef;

        const adapter = self.mlysdk.driver.extensions.DPlayerHlsPlayerPlugin.create({
            container: video,
            ...this.options
        });

        this.dp = adapter.player;
    },
    async beforeUnmount() {
        if (this.dp) this.dp.destroy();
    }
};
</script>

// Web SDK/Player Integrations/RMP/React/html/src/components/Player.js
import {useEffect, useRef} from 'react';

const Player = (props) => {
    const videoRef = useRef(null);
    const playerRef = useRef(null);
    const {options} = props;

    useEffect(() => {
        if (!playerRef.current) {
            const adapter = self.mlysdk.driver.extensions.RadiantMPHlsPlayerPlugin.create(options);
            playerRef.current = adapter.player;
        } else {
            const player = playerRef.current;
            player.src(options.sources);
        }
    }, [options, videoRef]);

    useEffect(() => {
        const player = playerRef.current;
        return () => {
            if (player && !player.isDisposed()) {
                player.dispose();
                playerRef.current = null;
            }
        };
    }, [playerRef]);

    return <div ref={videoRef} id="video" style={{width: "100%", maxWidth: "800px"}} />;
};

export default Player;
