// Web SDK/Player Integrations/HLS.js/Vue/html/src/components/Player.vue
<template>
    <video id="video" ref="videoRef" controls autoplay width=800 />
</template>

<script>
/* eslint-disable vue/multi-word-component-names */

export default {
    name: 'Player',
    props: {
        options: {
            type: Object
        }
    },
    data() {
        return {
            hls: null
        };
    },
    async mounted() {
        const video = this.$refs.videoRef;
        const {sourceUrl} = this.options;
        const adapter = self.mlysdk.driver.extensions.HlsjsHlsPlayerPlugin.create({
            url: sourceUrl,
            element: video
        });
        this.hls = adapter.protocol;
    },
    async beforeUnmount() {
        if (this.hls) {
            this.hls.destroy();
        }
    }
};
</script>

// Web SDK/Player Integrations/HLS.js/React/html/src/components/Player.js
import {useEffect, useRef} from 'react';

const Player = (props) => {
    const videoRef = useRef(null);
    const hlsRef = useRef(null);

    useEffect(() => {
        const {sourceUrl} = props.options;
        const video = videoRef.current;
        if (!hlsRef.current) {
            const adapter = self.mlysdk.driver.extensions.HlsjsHlsPlayerPlugin.create({
                url: sourceUrl,
                element: video
            });
            hlsRef.current = adapter.protocol;
        }
    }, [videoRef]);

    useEffect(() => {
        const hls = hlsRef.current;
        return () => {
            if (hls) {
                hls.destroy();
                hlsRef.current = null;
            }
        };
    }, [hlsRef]);

    return (
        <video
            controls
            autoPlay
            ref={videoRef}

            width={800}
        />
    );
};

export default Player;
